services:
  - type: web
    name: chaoyun-mall-api
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    healthCheckPath: /api/health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chaoyun-mall-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: CORS_ALLOWED_ORIGINS
        value: https://sparkly-clafoutis-2d38af.netlify.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://sparkly-clafoutis-2d38af.netlify.app
      - key: PYTHON_VERSION
        value: 3.13.5

databases:
  - name: chaoyun-mall-db
    plan: free
    region: singapore
    databaseName: chaoyun_mall
    user: chaoyun_mall
