# Generated by Django 6.1 on 2026-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='称呼')),
                ('contact', models.CharField(max_length=160, verbose_name='联系方式')),
                ('cooperation_type', models.CharField(choices=[('school', 'B 端校园研学'), ('family', 'C 端家庭体验'), ('tourism', 'G 端文旅合作'), ('licensing', 'B2B 纹样授权')], max_length=20, verbose_name='合作方向')),
                ('message', models.TextField(blank=True, verbose_name='合作留言')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('contacted', '已联系'), ('closed', '已完成')], default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '合作意向',
                'verbose_name_plural': '合作意向',
                'ordering': ('-created_at',),
            },
        ),
    ]
